#ifndef DBCSTRUCTURE_REFERENCE_H
#define DBCSTRUCTURE_REFERENCE_H

// AUTO-GENERATED by CoreAlign/tools/gen_reference.py -- DO NOT EDIT.
// Inert reference map of the TBC 2.4.3.8606 client DBC tables the core does NOT model.
// This header is never #included; activating a table = move its struct into
// DBCStructure.h, add its fmt to DBCfmt.h, and a DBCStorage loader.

/*
 * DBC MAP -- 185 client TBC tables (build 2.4.3.8606)
 *   ACTIVE = modelled + loaded in DBCStructure.h ; DOC = inert reference here.
 *
 *   AnimationData                DOC   (7 cols)
 *   AreaPOI                      DOC   (45 cols)
 *   AreaTable                    ACTIVE
 *   AreaTrigger                  ACTIVE
 *   AttackAnimKits               DOC   (5 cols)
 *   AttackAnimTypes              DOC   (2 cols)
 *   AuctionHouse                 ACTIVE
 *   BankBagSlotPrices            ACTIVE
 *   BattlemasterList             ACTIVE
 *   CameraShakes                 DOC   (8 cols)
 *   Cfg_Categories               DOC   (21 cols)
 *   Cfg_Configs                  DOC   (4 cols)
 *   CharBaseInfo                 DOC   (2 cols)
 *   CharHairGeosets              DOC   (6 cols)
 *   CharHairTextures             DOC   (8 cols)
 *   CharSections                 DOC   (10 cols)
 *   CharStartOutfit              ACTIVE
 *   CharTitles                   ACTIVE
 *   CharVariations               DOC   (6 cols)
 *   CharacterFacialHairStyles    DOC   (11 cols)
 *   ChatChannels                 ACTIVE
 *   ChatProfanity                DOC   (3 cols)
 *   ChrClasses                   ACTIVE
 *   ChrRaces                     ACTIVE
 *   CinematicCamera              DOC   (7 cols)
 *   CinematicSequences           ACTIVE
 *   CreatureDisplayInfo          ACTIVE
 *   CreatureDisplayInfoExtra     ACTIVE
 *   CreatureFamily               ACTIVE
 *   CreatureModelData            DOC   (24 cols)
 *   CreatureSoundData            DOC   (37 cols)
 *   CreatureSpellData            ACTIVE
 *   CreatureType                 ACTIVE
 *   DeathThudLookups             DOC   (5 cols)
 *   DeclinedWord                 DOC   (2 cols)
 *   DeclinedWordCases            DOC   (4 cols)
 *   DurabilityCosts              ACTIVE
 *   DurabilityQuality            ACTIVE
 *   Emotes                       ACTIVE
 *   EmotesText                   ACTIVE
 *   EmotesTextData               DOC   (18 cols)
 *   EmotesTextSound              DOC   (5 cols)
 *   EnvironmentalDamage          DOC   (3 cols)
 *   Exhaustion                   DOC   (23 cols)
 *   Faction                      ACTIVE
 *   FactionGroup                 DOC   (20 cols)
 *   FactionTemplate              ACTIVE
 *   FootprintTextures            DOC   (2 cols)
 *   FootstepTerrainLookup        DOC   (5 cols)
 *   GMSurveyCurrentSurvey        DOC   (2 cols)
 *   GMSurveyQuestions            DOC   (18 cols)
 *   GMSurveySurveys              DOC   (11 cols)
 *   GMTicketCategory             DOC   (18 cols)
 *   GameObjectArtKit             DOC   (8 cols)
 *   GameObjectDisplayInfo        ACTIVE
 *   GameTables                   DOC   (3 cols)
 *   GameTips                     DOC   (18 cols)
 *   GemProperties                ACTIVE
 *   GroundEffectDoodad           DOC   (3 cols)
 *   GroundEffectTexture          DOC   (7 cols)
 *   GtChanceToMeleeCrit          ACTIVE
 *   GtChanceToMeleeCritBase      ACTIVE
 *   GtChanceToSpellCrit          ACTIVE
 *   GtChanceToSpellCritBase      ACTIVE
 *   GtCombatRatings              ACTIVE
 *   GtOCTRegenHP                 ACTIVE
 *   GtRegenHPPerSpt              ACTIVE
 *   GtRegenMPPerSpt              ACTIVE
 *   HelmetGeosetVisData          DOC   (8 cols)
 *   Item                         ACTIVE
 *   ItemBagFamily                ACTIVE
 *   ItemClass                    ACTIVE
 *   ItemCondExtCosts             DOC   (4 cols)
 *   ItemDisplayInfo              DOC   (25 cols)
 *   ItemExtendedCost             ACTIVE
 *   ItemGroupSounds              DOC   (5 cols)
 *   ItemPetFood                  DOC   (18 cols)
 *   ItemRandomProperties         ACTIVE
 *   ItemRandomSuffix             ACTIVE
 *   ItemSet                      ACTIVE
 *   ItemSubClass                 DOC   (44 cols)
 *   ItemSubClassMask             DOC   (19 cols)
 *   ItemVisualEffects            DOC   (2 cols)
 *   ItemVisuals                  DOC   (6 cols)
 *   LFGDungeons                  DOC   (24 cols)
 *   LanguageWords                DOC   (3 cols)
 *   Languages                    DOC   (18 cols)
 *   Light                        DOC   (12 cols)
 *   LightFloatBand               DOC   (34 cols)
 *   LightIntBand                 DOC   (34 cols)
 *   LightParams                  DOC   (9 cols)
 *   LightSkybox                  DOC   (3 cols)
 *   LiquidType                   ACTIVE
 *   LoadingScreenTaxiSplines     DOC   (19 cols)
 *   LoadingScreens               DOC   (3 cols)
 *   Lock                         ACTIVE
 *   LockType                     DOC   (53 cols)
 *   MailTemplate                 ACTIVE
 *   Map                          ACTIVE
 *   Material                     DOC   (5 cols)
 *   NPCSounds                    DOC   (5 cols)
 *   NameGen                      DOC   (4 cols)
 *   NamesProfanity               DOC   (3 cols)
 *   NamesReserved                DOC   (3 cols)
 *   Package                      DOC   (20 cols)
 *   PageTextMaterial             DOC   (2 cols)
 *   PaperDollItemFrame           DOC   (3 cols)
 *   ParticleColor                DOC   (10 cols)
 *   PetLoyalty                   DOC   (18 cols)
 *   PetPersonality               DOC   (27 cols)
 *   PetitionType                 DOC   (3 cols)
 *   QuestInfo                    DOC   (18 cols)
 *   QuestSort                    ACTIVE
 *   RandomPropertiesPoints       ACTIVE
 *   Resistances                  DOC   (20 cols)
 *   ServerMessages               DOC   (18 cols)
 *   SheatheSoundLookups          DOC   (7 cols)
 *   SkillCostsData               DOC   (5 cols)
 *   SkillLine                    ACTIVE
 *   SkillLineAbility             ACTIVE
 *   SkillLineCategory            DOC   (19 cols)
 *   SkillRaceClassInfo           ACTIVE
 *   SkillTiers                   DOC   (33 cols)
 *   SoundAmbience                DOC   (3 cols)
 *   SoundEntries                 ACTIVE
 *   SoundProviderPreferences     DOC   (24 cols)
 *   SoundSamplePreferences       DOC   (17 cols)
 *   SoundWaterType               DOC   (4 cols)
 *   SpamMessages                 DOC   (2 cols)
 *   Spell                        ACTIVE
 *   SpellCastTime                ACTIVE
 *   SpellCategory                DOC   (2 cols)
 *   SpellChainEffects            DOC   (47 cols)
 *   SpellDispelType              DOC   (21 cols)
 *   SpellDuration                ACTIVE
 *   SpellEffectCameraShakes      DOC   (4 cols)
 *   SpellFocusObject             ACTIVE
 *   SpellIcon                    DOC   (2 cols)
 *   SpellItemEnchantment         ACTIVE
 *   SpellItemEnchantmentCondition ACTIVE
 *   SpellMechanic                DOC   (18 cols)
 *   SpellMissileMotion           DOC   (5 cols)
 *   SpellRadius                  ACTIVE
 *   SpellRange                   ACTIVE
 *   SpellShapeshift              ACTIVE
 *   SpellVisual                  DOC   (25 cols)
 *   SpellVisualEffectName        DOC   (5 cols)
 *   SpellVisualKit               DOC   (38 cols)
 *   SpellVisualPrecastTransitions DOC   (3 cols)
 *   StableSlotPrices             ACTIVE
 *   Startup_Strings              DOC   (19 cols)
 *   Stationery                   DOC   (4 cols)
 *   StringLookups                DOC   (2 cols)
 *   SummonProperties             ACTIVE
 *   Talent                       ACTIVE
 *   TalentTab                    ACTIVE
 *   TaxiNodes                    ACTIVE
 *   TaxiPath                     ACTIVE
 *   TaxiPathNode                 ACTIVE
 *   TerrainType                  DOC   (6 cols)
 *   TerrainTypeSounds            DOC   (1 cols)
 *   TotemCategory                ACTIVE
 *   TransportAnimation           DOC   (7 cols)
 *   TransportPhysics             DOC   (11 cols)
 *   UISoundLookups               DOC   (3 cols)
 *   UnitBlood                    DOC   (10 cols)
 *   UnitBloodLevels              DOC   (4 cols)
 *   VideoHardware                DOC   (23 cols)
 *   VocalUISounds                DOC   (7 cols)
 *   WMOAreaTable                 ACTIVE
 *   WeaponImpactSounds           DOC   (23 cols)
 *   WeaponSwingSounds2           DOC   (4 cols)
 *   Weather                      DOC   (7 cols)
 *   WorldMapArea                 ACTIVE
 *   WorldMapContinent            DOC   (13 cols)
 *   WorldMapOverlay              DOC   (17 cols)
 *   WorldMapTransforms           DOC   (9 cols)
 *   WorldSafeLocs                ACTIVE
 *   WorldStateUI                 DOC   (63 cols)
 *   WorldStateZoneSounds         DOC   (8 cols)
 *   WowError_Strings             DOC   (19 cols)
 *   ZoneIntroMusicTable          DOC   (5 cols)
 *   ZoneMusic                    DOC   (8 cols)
 *   gtNPCManaCostScaler          DOC   (1 cols)
 *   gtOCTRegenMP                 DOC   (1 cols)
 *
 *   (69 ACTIVE, 116 DOC)
 */

// AnimationData -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct AnimationDataEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    uint32  Weaponflags;  // [dbd-only] 2
    uint32  Bodyflags;  // [dbd-only] 3
    int32   Field_0_7_0_3694_004;  // 4
    uint32  Flags;  // [dbd-only] 5
    uint32  Fallback;  // [dbd-only] 6
};

// AreaPOI -- 45 cols, record_size 180, build 2.4.3.8606. INERT reference (not loaded).
struct AreaPOIEntry
{
    int32   ID;  // 0
    int32   Importance;  // 1
    int32   Icon;  // 2
    int32   FactionID;  // 3
    float   Pos[3];  // 4-6
    int32   ContinentID;  // 7
    int32   Flags;  // 8
    int32   AreaID;  // 9
    char*   Name_lang[16];  // 10-25
// uint32  Name_lang_flags;  // 26
    char*   Description_lang[16];  // 27-42
// uint32  Description_lang_flags;  // 43
    int32   WorldStateID;  // 44
};

// AttackAnimKits -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct AttackAnimKitsEntry
{
    uint32  ID;  // 0
    uint32  ItemSubclassID;  // 1
    uint32  AnimTypeID;  // 2
    uint32  AnimFrequency;  // 3
    uint32  WhichHand;  // 4
};

// AttackAnimTypes -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct AttackAnimTypesEntry
{
    uint32  AnimID;  // 0
    char*   AnimName;  // 1
};

// CameraShakes -- 8 cols, record_size 32, build 2.4.3.8606. INERT reference (not loaded).
struct CameraShakesEntry
{
    int32   ID;  // 0
    int32   ShakeType;  // 1
    int32   Direction;  // 2
    float   Amplitude;  // 3
    float   Frequency;  // 4
    float   Duration;  // 5
    float   Phase;  // 6
    float   Coefficient;  // 7
};

// Cfg_Categories -- 21 cols, record_size 84, build 2.4.3.8606. INERT reference (not loaded).
struct Cfg_CategoriesEntry
{
    uint32  Id;  // 0
    uint32  LocaleMask;  // 1
    uint32  CreateCharsetMask;  // 2
    uint32  Flags;  // 3
    char*   Name_lang[16];  // 4-19
// uint32  Name_lang_flags;  // 20
};

// Cfg_Configs -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct Cfg_ConfigsEntry
{
    uint32  Id;  // 0
    uint32  Type;  // 1
    uint32  IsPvp;  // 2
    uint32  IsRp;  // 3
};

// CharBaseInfo -- 2 cols, record_size 2, build 2.4.3.8606. INERT reference (not loaded).
struct CharBaseInfoEntry
{
    uint8   RaceID;  // 0
    uint8   ClassID;  // 1
};

// CharHairGeosets -- 6 cols, record_size 24, build 2.4.3.8606. INERT reference (not loaded).
struct CharHairGeosetsEntry
{
    uint32  ID;  // [dbd-only] 0
    uint32  RaceID;  // [dbd-only] 1
    uint32  SexID;  // [dbd-only] 2
    uint32  VariationID;  // [dbd-only] 3
    uint32  GeosetID;  // [dbd-only] 4
    uint32  Showscalp;  // [dbd-only] 5
};

// CharHairTextures -- 8 cols, record_size 32, build 2.4.3.8606. INERT reference (not loaded).
struct CharHairTexturesEntry
{
    uint32  Id;  // [dbd-only] 0
    uint32  Race;  // [dbd-only] 1
    uint32  Gender;  // [dbd-only] 2
    uint32  Field_003;  // [dbd-only] 3
    uint32  MaybeRaceMask;  // [dbd-only] 4
    int32   HairTextureXIndex;  // [dbd-only] 5
    int32   Field_006;  // [dbd-only] 6
    int32   Field_007;  // [dbd-only] 7
};

// CharSections -- 10 cols, record_size 40, build 2.4.3.8606. INERT reference (not loaded).
struct CharSectionsEntry
{
    uint32  ID;  // 0
    uint32  RaceID;  // 1
    uint32  SexID;  // 2
    uint32  BaseSection;  // 3
    uint32  VariationIndex;  // 4
    uint32  ColorIndex;  // 5
    char*   TextureName[3];  // 6-8
    uint32  Flags;  // 9
};

// CharVariations -- 6 cols, record_size 24, build 2.4.3.8606. INERT reference (not loaded).
struct CharVariationsEntry
{
    uint32  RaceID;  // 0
    uint32  SexID;  // 1
    uint32  TextureHoldLayer[4];  // 2-5
};

// CharacterFacialHairStyles -- 11 cols, record_size 44, build 2.4.3.8606. INERT reference (not loaded).
struct CharacterFacialHairStylesEntry
{
    int32   RaceID;  // 0
    int32   SexID;  // 1
    int32   VariationID;  // 2
    int32   Geoset[8];  // 3-10
};

// ChatProfanity -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct ChatProfanityEntry
{
    int32   ID;  // 0
    char*   Text;  // 1
    int32   Language;  // 2
};

// CinematicCamera -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct CinematicCameraEntry
{
    uint32  id;  // 0
    char*   model;  // 1
    uint32  sound_id;  // 2
    float   origin_x;  // 3
    float   origin_y;  // 4
    float   origin_z;  // 5
    float   origin_facing;  // 6
};

// CreatureModelData -- 24 cols, record_size 96, build 2.4.3.8606. INERT reference (not loaded).
struct CreatureModelDataEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
    char*   ModelName;  // 2
    int32   SizeClass;  // 3
    float   ModelScale;  // 4
    int32   BloodID;  // 5
    int32   FootprintTextureID;  // 6
    float   FootprintTextureLength;  // 7
    float   FootprintTextureWidth;  // 8
    float   FootprintParticleScale;  // 9
    int32   FoleyMaterialID;  // [dbd-only] 10
    int32   FootstepShakeSize;  // 11
    int32   DeathThudShakeSize;  // 12
    int32   SoundID;  // 13
    float   CollisionWidth;  // 14
    float   CollisionHeight;  // 15
    float   MountHeight;  // 16
    float   GeoBox[6];  // 17-22
    float   AttachedEffectScale;  // 23
};

// CreatureSoundData -- 37 cols, record_size 148, build 2.4.3.8606. INERT reference (not loaded).
struct CreatureSoundDataEntry
{
    int32   ID;  // 0
    int32   SoundExertionID;  // 1
    int32   SoundExertionCriticalID;  // 2
    int32   SoundInjuryID;  // 3
    int32   SoundInjuryCriticalID;  // 4
    int32   SoundInjuryCrushingBlowID;  // 5
    int32   SoundDeathID;  // 6
    int32   SoundStunID;  // 7
    int32   SoundStandID;  // 8
    int32   SoundFootstepID;  // 9
    int32   SoundAggroID;  // 10
    int32   SoundWingFlapID;  // 11
    int32   SoundWingGlideID;  // 12
    int32   SoundAlertID;  // 13
    int32   SoundFidget[5];  // 14-18
    int32   CustomAttack[4];  // 19-22
    int32   NPCSoundID;  // 23
    int32   LoopSoundID;  // 24
    int32   CreatureImpactType;  // 25
    int32   SoundJumpStartID;  // 26
    int32   SoundJumpEndID;  // 27
    int32   SoundPetAttackID;  // 28
    int32   SoundPetOrderID;  // 29
    int32   SoundPetDismissID;  // 30
    float   FidgetDelaySecondsMin;  // 31
    float   FidgetDelaySecondsMax;  // 32
    int32   BirthSoundID;  // 33
    int32   SpellCastDirectedSoundID;  // 34
    int32   SubmergeSoundID;  // 35
    int32   SubmergedSoundID;  // 36
};

// DeathThudLookups -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct DeathThudLookupsEntry
{
    uint32  ID;  // 0
    uint32  SizeClass;  // 1
    uint32  TerrainTypeSoundID;  // 2
    uint32  SoundEntryID;  // 3
    uint32  SoundEntryIDWater;  // 4
};

// DeclinedWord -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct DeclinedWordEntry
{
    uint32  ID;  // 0
    char*   Word;  // 1
};

// DeclinedWordCases -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct DeclinedWordCasesEntry
{
    uint32  ID;  // 0
    uint32  DeclinedWordID;  // 1
    uint32  CaseIndex;  // 2
    char*   DeclinedWord;  // 3
};

// EmotesTextData -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct EmotesTextDataEntry
{
    uint32  ID;  // 0
    char*   Text_lang[16];  // 1-16
// uint32  Text_lang_flags;  // 17
};

// EmotesTextSound -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct EmotesTextSoundEntry
{
    uint32  ID;  // 0
    uint32  EmotesTextID;  // 1
    uint32  RaceID;  // 2
    uint32  SexID;  // 3
    uint32  SoundID;  // 4
};

// EnvironmentalDamage -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct EnvironmentalDamageEntry
{
    uint32  ID;  // 0
    uint32  EnumID;  // 1
    uint32  VisualKitID;  // 2
};

// Exhaustion -- 23 cols, record_size 92, build 2.4.3.8606. INERT reference (not loaded).
struct ExhaustionEntry
{
    int32   ID;  // 0
    int32   Xp;  // 1
    float   Factor;  // 2
    float   OutdoorHours;  // 3
    float   InnHours;  // 4
    char*   Name_lang[16];  // 5-20
// uint32  Name_lang_flags;  // 21
    float   Threshold;  // 22
};

// FactionGroup -- 20 cols, record_size 80, build 2.4.3.8606. INERT reference (not loaded).
struct FactionGroupEntry
{
    uint32  ID;  // 0
    uint32  MaskID;  // 1
    char*   InternalName;  // 2
    char*   Name_lang[16];  // 3-18
// uint32  Name_lang_flags;  // 19
};

// FootprintTextures -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct FootprintTexturesEntry
{
    uint32  ID;  // 0
    char*   FootstepFilename;  // 1
};

// FootstepTerrainLookup -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct FootstepTerrainLookupEntry
{
    uint32  ID;  // 0
    uint32  CreatureFootstepID;  // 1
    uint32  TerrainSoundID;  // 2
    uint32  SoundID;  // 3
    uint32  SoundIDSplash;  // 4
};

// GMSurveyCurrentSurvey -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct GMSurveyCurrentSurveyEntry
{
    uint32  LangID;  // 0
    uint32  GMSurveyID;  // 1
};

// GMSurveyQuestions -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct GMSurveyQuestionsEntry
{
    int32   ID;  // 0
    char*   Question_lang[16];  // 1-16
// uint32  Question_lang_flags;  // 17
};

// GMSurveySurveys -- 11 cols, record_size 44, build 2.4.3.8606. INERT reference (not loaded).
struct GMSurveySurveysEntry
{
    uint32  ID;  // 0
    uint32  Q[10];  // 1-10
};

// GMTicketCategory -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct GMTicketCategoryEntry
{
    uint32  ID;  // 0
    char*   Category_lang[16];  // 1-16
// uint32  Category_lang_flags;  // 17
};

// GameObjectArtKit -- 8 cols, record_size 32, build 2.4.3.8606. INERT reference (not loaded).
struct GameObjectArtKitEntry
{
    uint32  ID;  // 0
    char*   TextureVariation[3];  // 1-3
    char*   AttachModel[4];  // 4-7
};

// GameTables -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct GameTablesEntry
{
    char*   Name;  // 0
    int32   NumRows;  // 1
    int32   NumColumns;  // 2
};

// GameTips -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct GameTipsEntry
{
    uint32  ID;  // 0
    char*   Text_lang[16];  // 1-16
// uint32  Text_lang_flags;  // 17
};

// GroundEffectDoodad -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct GroundEffectDoodadEntry
{
    uint32  ID;  // 0
    uint32  DoodadIdTag;  // 1
    char*   Doodadpath;  // 2
};

// GroundEffectTexture -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct GroundEffectTextureEntry
{
    uint32  ID;  // 0
    uint32  DoodadID[4];  // 1-4
    uint32  Density;  // 5
    uint32  Sound;  // 6
};

// HelmetGeosetVisData -- 8 cols, record_size 32, build 2.4.3.8606. INERT reference (not loaded).
struct HelmetGeosetVisDataEntry
{
    uint32  ID;  // 0
    uint32  HideGeoset[7];  // 1-7
};

// ItemCondExtCosts -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct ItemCondExtCostsEntry
{
    uint32  ID;  // 0
    uint32  CondExtendedCost;  // 1
    uint32  ItemExtendedCostEntry;  // 2
    uint32  ArenaSeason;  // 3
};

// ItemDisplayInfo -- 25 cols, record_size 100, build 2.4.3.8606. INERT reference (not loaded).
struct ItemDisplayInfoEntry
{
    uint32  ID;  // 0
    char*   ModelName[2];  // 1-2
    char*   ModelTexture[2];  // 3-4
    char*   InventoryIcon[2];  // 5-6
    uint32  GeosetGroup[3];  // 7-9
    uint32  Flags;  // 10
    uint32  SpellVisualID;  // 11
    uint32  GroupSoundIndex;  // 12
    uint32  HelmetGeosetVisID[2];  // 13-14
    char*   Texture[8];  // 15-22
    uint32  ItemVisual;  // 23
    uint32  ParticleColorID;  // 24
};

// ItemGroupSounds -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct ItemGroupSoundsEntry
{
    uint32  ID;  // 0
    uint32  Sound[4];  // 1-4
};

// ItemPetFood -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct ItemPetFoodEntry
{
    int32   ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
};

// ItemSubClass -- 44 cols, record_size 176, build 2.4.3.8606. INERT reference (not loaded).
struct ItemSubClassEntry
{
    int32   ClassID;  // 0
    int32   SubClassID;  // 1
    int32   PrerequisiteProficiency;  // 2
    int32   PostrequisiteProficiency;  // 3
    int32   Flags;  // 4
    int32   DisplayFlags;  // 5
    int32   WeaponParrySeq;  // 6
    int32   WeaponReadySeq;  // 7
    int32   WeaponAttackSeq;  // 8
    int32   WeaponSwingSize;  // 9
    char*   DisplayName_lang[16];  // 10-25
// uint32  DisplayName_lang_flags;  // 26
    char*   VerboseName_lang[16];  // 27-42
// uint32  VerboseName_lang_flags;  // 43
};

// ItemSubClassMask -- 19 cols, record_size 76, build 2.4.3.8606. INERT reference (not loaded).
struct ItemSubClassMaskEntry
{
    int32   ClassID;  // 0
    int32   Mask;  // 1
    char*   Name_lang[16];  // 2-17
// uint32  Name_lang_flags;  // 18
};

// ItemVisualEffects -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct ItemVisualEffectsEntry
{
    int32   ID;  // 0
    char*   Model;  // 1
};

// ItemVisuals -- 6 cols, record_size 24, build 2.4.3.8606. INERT reference (not loaded).
struct ItemVisualsEntry
{
    int32   ID;  // 0
    int32   Slot[5];  // 1-5
};

// LFGDungeons -- 24 cols, record_size 96, build 2.4.3.8606. INERT reference (not loaded).
struct LFGDungeonsEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    int32   MinLevel;  // 18
    int32   MaxLevel;  // 19
    int32   TypeID;  // 20
    int32   Faction;  // 21
    char*   TextureFilename;  // 22
    int32   ExpansionLevel;  // 23
};

// LanguageWords -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct LanguageWordsEntry
{
    uint32  ID;  // 0
    uint32  LanguageID;  // 1
    char*   Word;  // 2
};

// Languages -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct LanguagesEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
};

// Light -- 12 cols, record_size 48, build 2.4.3.8606. INERT reference (not loaded).
struct LightEntry
{
    int32   ID;  // 0
    int32   ContinentID;  // 1
    float   GameCoords[3];  // 2-4
    float   GameFalloffStart;  // 5
    float   GameFalloffEnd;  // 6
    int32   LightParamsID[5];  // 7-11
};

// LightFloatBand -- 34 cols, record_size 136, build 2.4.3.8606. INERT reference (not loaded).
struct LightFloatBandEntry
{
    uint32  ID;  // 0
    uint32  Num;  // 1
    uint32  Time[16];  // 2-17
    float   Data[16];  // 18-33
};

// LightIntBand -- 34 cols, record_size 136, build 2.4.3.8606. INERT reference (not loaded).
struct LightIntBandEntry
{
    uint32  ID;  // 0
    uint32  Num;  // 1
    uint32  Time[16];  // 2-17
    uint32  Data[16];  // 18-33
};

// LightParams -- 9 cols, record_size 36, build 2.4.3.8606. INERT reference (not loaded).
struct LightParamsEntry
{
    int32   ID;  // 0
    int32   HighlightSky;  // 1
    int32   LightSkyboxID;  // 2
    float   Glow;  // 3
    float   WaterShallowAlpha;  // 4
    float   WaterDeepAlpha;  // 5
    float   OceanShallowAlpha;  // 6
    float   OceanDeepAlpha;  // 7
    int32   Flags;  // 8
};

// LightSkybox -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct LightSkyboxEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  Flags;  // 2
};

// LoadingScreenTaxiSplines -- 19 cols, record_size 76, build 2.4.3.8606. INERT reference (not loaded).
struct LoadingScreenTaxiSplinesEntry
{
    int32   ID;  // 0
    int32   PathID;  // 1
    float   Locx[8];  // 2-9
    float   Locy[8];  // 10-17
    int32   LegIndex;  // 18
};

// LoadingScreens -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct LoadingScreensEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    char*   FileName;  // 2
};

// LockType -- 53 cols, record_size 212, build 2.4.3.8606. INERT reference (not loaded).
struct LockTypeEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    char*   ResourceName_lang[16];  // 18-33
// uint32  ResourceName_lang_flags;  // 34
    char*   Verb_lang[16];  // 35-50
// uint32  Verb_lang_flags;  // 51
    char*   CursorName;  // 52
};

// Material -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct MaterialEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
    uint32  FoleySoundID;  // 2
    uint32  SheatheSoundID;  // 3
    uint32  UnsheatheSoundID;  // 4
};

// NPCSounds -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct NPCSoundsEntry
{
    uint32  ID;  // 0
    uint32  SoundID[4];  // [dbd-only] 1-4
};

// NameGen -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct NameGenEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Name;  // [dbd-only] 1
    uint32  RaceID;  // [dbd-only] 2
    uint32  Sex;  // [dbd-only] 3
};

// NamesProfanity -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct NamesProfanityEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    int32   Language;  // 2
};

// NamesReserved -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct NamesReservedEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    int32   Language;  // 2
};

// Package -- 20 cols, record_size 80, build 2.4.3.8606. INERT reference (not loaded).
struct PackageEntry
{
    int32   ID;  // 0
    char*   Icon;  // 1
    int32   Cost;  // 2
    char*   Name_lang[16];  // 3-18
// uint32  Name_lang_flags;  // 19
};

// PageTextMaterial -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct PageTextMaterialEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
};

// PaperDollItemFrame -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct PaperDollItemFrameEntry
{
    char*   ItemButtonName;  // 0
    char*   SlotIcon;  // 1
    int32   SlotNumber;  // 2
};

// ParticleColor -- 10 cols, record_size 40, build 2.4.3.8606. INERT reference (not loaded).
struct ParticleColorEntry
{
    uint32  ID;  // 0
    int32   Start[3];  // 1-3
    int32   Mid[3];  // 4-6
    int32   End[3];  // 7-9
};

// PetLoyalty -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct PetLoyaltyEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
};

// PetPersonality -- 27 cols, record_size 108, build 2.4.3.8606. INERT reference (not loaded).
struct PetPersonalityEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    int32   HappinessThreshold[3];  // 18-20
    float   HappinessDamage[3];  // 21-23
    float   DamageModifier[3];  // 24-26
};

// PetitionType -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct PetitionTypeEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    uint32  Type;  // 2
};

// QuestInfo -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct QuestInfoEntry
{
    int32   ID;  // 0
    char*   InfoName_lang[16];  // [dbd-only] 1-16
// uint32  InfoName_lang_flags;  // 17
};

// Resistances -- 20 cols, record_size 80, build 2.4.3.8606. INERT reference (not loaded).
struct ResistancesEntry
{
    int32   ID;  // 0
    int32   Flags;  // 1
    int32   FizzleSoundID;  // 2
    char*   Name_lang[16];  // 3-18
// uint32  Name_lang_flags;  // 19
};

// ServerMessages -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct ServerMessagesEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Text_lang[16];  // 1-16
// uint32  Text_lang_flags;  // 17
};

// SheatheSoundLookups -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct SheatheSoundLookupsEntry
{
    uint32  ID;  // 0
    int32   ClassID;  // 1
    int32   SubclassID;  // 2
    int32   Material;  // 3
    int32   CheckMaterial;  // 4
    int32   SheatheSound;  // 5
    int32   UnsheatheSound;  // 6
};

// SkillCostsData -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct SkillCostsDataEntry
{
    uint32  ID;  // 0
    uint32  SkillCostsID;  // 1
    uint32  Cost[3];  // 2-4
};

// SkillLineCategory -- 19 cols, record_size 76, build 2.4.3.8606. INERT reference (not loaded).
struct SkillLineCategoryEntry
{
    uint32  id;  // [dbd-only] 0
    char*   name_lang[16];  // 1-16
// uint32  name_lang_flags;  // 17
    int32   sort_index;  // 18
};

// SkillTiers -- 33 cols, record_size 132, build 2.4.3.8606. INERT reference (not loaded).
struct SkillTiersEntry
{
    uint32  ID;  // 0
    uint32  Cost[16];  // 1-16
    uint32  Value[16];  // 17-32
};

// SoundAmbience -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct SoundAmbienceEntry
{
    uint32  ID;  // 0
    uint32  AmbienceID[2];  // 1-2
};

// SoundProviderPreferences -- 24 cols, record_size 96, build 2.4.3.8606. INERT reference (not loaded).
struct SoundProviderPreferencesEntry
{
    int32   ID;  // 0
    char*   Description;  // 1
    int32   Flags;  // 2
    int32   EAXEnvironmentSelection;  // 3
    float   EAXDecayTime;  // 4
    float   EAX2EnvironmentSize;  // 5
    float   EAX2EnvironmentDiffusion;  // 6
    int32   EAX2Room;  // 7
    int32   EAX2RoomHF;  // 8
    float   EAX2DecayHFRatio;  // 9
    int32   EAX2Reflections;  // 10
    float   EAX2ReflectionsDelay;  // 11
    int32   EAX2Reverb;  // 12
    float   EAX2ReverbDelay;  // 13
    float   EAX2RoomRolloff;  // 14
    float   EAX2AirAbsorption;  // 15
    int32   EAX3RoomLF;  // 16
    float   EAX3DecayLFRatio;  // 17
    float   EAX3EchoTime;  // 18
    float   EAX3EchoDepth;  // 19
    float   EAX3ModulationTime;  // 20
    float   EAX3ModulationDepth;  // 21
    float   EAX3HFReference;  // 22
    float   EAX3LFReference;  // 23
};

// SoundSamplePreferences -- 17 cols, record_size 68, build 2.4.3.8606. INERT reference (not loaded).
struct SoundSamplePreferencesEntry
{
    uint32  ID;  // 0
    int32   Field_0_6_0_3592_001;  // 1
    int32   Field_0_6_0_3592_002;  // 2
    int32   EAX2SampleRoom;  // 3
    int32   Field_0_6_0_3592_004;  // 4
    int32   Field_0_6_0_3592_005;  // 5
    float   Field_0_6_0_3592_006;  // 6
    int32   Field_0_6_0_3592_007;  // 7
    float   EAX2SampleOcclusionLFRatio;  // 8
    float   EAX2SampleOcclusionRoomRatio;  // 9
    int32   Field_0_6_0_3592_010;  // 10
    float   EAX1EffectLevel;  // 11
    int32   Field_0_6_0_3592_012;  // 12
    float   Field_0_6_0_3592_013;  // 13
    float   EAX3SampleExclusion;  // 14
    float   Field_0_6_0_3592_015;  // 15
    int32   Field_0_6_0_3592_016;  // 16
};

// SoundWaterType -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct SoundWaterTypeEntry
{
    int32   ID;  // 0
    int32   SoundType;  // 1
    int32   SoundSubtype;  // 2
    int32   SoundID;  // 3
};

// SpamMessages -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct SpamMessagesEntry
{
    uint32  ID;  // 0
    char*   Text;  // 1
};

// SpellCategory -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct SpellCategoryEntry
{
    uint32  ID;  // 0
    uint32  Flags;  // 1
};

// SpellChainEffects -- 47 cols, record_size 173, build 2.4.3.8606. INERT reference (not loaded).
struct SpellChainEffectsEntry
{
    uint32  ID;  // [dbd-only] 0
    float   AvgSegLen;  // 1
    float   Width;  // 2
    float   NoiseScale;  // 3
    float   TexCoordScale;  // 4
    int32   SegDuration;  // 5
    int32   SegDelay;  // 6
    char*   Texture;  // 7
    uint32  Flags;  // [dbd-only] 8
    int32   JointCount;  // 9
    float   JointOffsetRadius;  // 10
    int32   JointsPerMinorJoint;  // 11
    int32   MinorJointsPerMajorJoint;  // 12
    float   MinorJointScale;  // 13
    float   MajorJointScale;  // 14
    float   JointMoveSpeed;  // 15
    float   JointSmoothness;  // 16
    float   MinDurationBetweenJointJumps;  // 17
    float   MaxDurationBetweenJointJumps;  // 18
    float   WaveHeight;  // 19
    float   WaveFreq;  // 20
    float   WaveSpeed;  // 21
    float   MinWaveAngle;  // 22
    float   MaxWaveAngle;  // 23
    float   MinWaveSpin;  // 24
    float   MaxWaveSpin;  // 25
    float   ArcHeight;  // 26
    float   MinArcAngle;  // 27
    float   MaxArcAngle;  // 28
    float   MinArcSpin;  // 29
    float   MaxArcSpin;  // 30
    float   DelayBetweenEffects;  // 31
    float   MinFlickerOnDuration;  // 32
    float   MaxFlickerOnDuration;  // 33
    float   MinFlickerOffDuration;  // 34
    float   MaxFlickerOffDuration;  // 35
    float   PulseSpeed;  // 36
    float   PulseOnLength;  // 37
    float   PulseFadeLength;  // 38
    uint8   Alpha;  // [dbd-only] 39
    uint8   Red;  // [dbd-only] 40
    uint8   Green;  // [dbd-only] 41
    uint8   Blue;  // [dbd-only] 42
    uint8   BlendMode;  // [dbd-only] 43
    char*   Combo;  // 44
    int32   RenderLayer;  // 45
    float   TextureLength;  // 46
};

// SpellDispelType -- 21 cols, record_size 84, build 2.4.3.8606. INERT reference (not loaded).
struct SpellDispelTypeEntry
{
    uint32  ID;  // 0
    char*   Name_lang[16];  // 1-16
// uint32  Name_lang_flags;  // 17
    uint32  Mask;  // 18
    int32   ImmunityPossible;  // 19
    char*   InternalName;  // 20
};

// SpellEffectCameraShakes -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct SpellEffectCameraShakesEntry
{
    int32   ID;  // 0
    int32   CameraShake[3];  // 1-3
};

// SpellIcon -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct SpellIconEntry
{
    uint32  ID;  // 0
    char*   TextureFilename;  // 1
};

// SpellMechanic -- 18 cols, record_size 72, build 2.4.3.8606. INERT reference (not loaded).
struct SpellMechanicEntry
{
    uint32  ID;  // 0
    char*   StateName_lang[16];  // [dbd-only] 1-16
// uint32  StateName_lang_flags;  // [dbd-only] 17
};

// SpellMissileMotion -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct SpellMissileMotionEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    char*   ScriptBody;  // 2
    int32   Flags;  // 3
    int32   MissileCount;  // 4
};

// SpellVisual -- 25 cols, record_size 100, build 2.4.3.8606. INERT reference (not loaded).
struct SpellVisualEntry
{
    uint32  ID;  // [dbd-only] 0
    uint32  PrecastKit;  // [dbd-only] 1
    uint32  CastKit;  // [dbd-only] 2
    uint32  ImpactKit;  // [dbd-only] 3
    uint32  StateKit;  // [dbd-only] 4
    uint32  ChannelKit;  // [dbd-only] 5
    uint32  HasMissile;  // [dbd-only] 6
    int32   MissileModel;  // 7
    uint32  MissilePathType;  // [dbd-only] 8
    uint32  MissileDestinationAttachment;  // [dbd-only] 9
    int32   MissileSound;  // 10
    int32   AnimEventSoundID;  // 11
    uint32  Flags;  // [dbd-only] 12
    uint32  CasterImpactKit;  // [dbd-only] 13
    uint32  TargetImpactKit;  // [dbd-only] 14
    int32   MissileAttachment;  // 15
    int32   MissileFollowGroundHeight;  // 16
    int32   MissileFollowGroundDropSpeed;  // 17
    int32   MissileFollowGroundApproach;  // 18
    uint32  MissileFollowGroundFlags;  // [dbd-only] 19
    int32   MissileMotion;  // 20
    uint32  MissileTargetingKit;  // [dbd-only] 21
    uint32  InstantAreaKit;  // [dbd-only] 22
    uint32  ImpactAreaKit;  // [dbd-only] 23
    uint32  PersistentAreaKit;  // [dbd-only] 24
};

// SpellVisualEffectName -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct SpellVisualEffectNameEntry
{
    uint32  ID;  // 0
    char*   Name;  // 1
    char*   FileName;  // 2
    float   AreaEffectSize;  // 3
    float   Scale;  // 4
};

// SpellVisualKit -- 38 cols, record_size 152, build 2.4.3.8606. INERT reference (not loaded).
struct SpellVisualKitEntry
{
    int32   ID;  // 0
    int32   KitType;  // 1
    int32   AnimID;  // 2
    int32   HeadEffect;  // 3
    int32   ChestEffect;  // 4
    int32   BaseEffect;  // 5
    int32   LeftHandEffect;  // 6
    int32   RightHandEffect;  // 7
    int32   BreathEffect;  // 8
    int32   LeftWeaponEffect;  // 9
    int32   RightWeaponEffect;  // 10
    int32   SpecialEffect[3];  // 11-13
    int32   WorldEffect;  // 14
    int32   SoundID;  // 15
    int32   ShakeID;  // 16
    int32   CharProc[4];  // 17-20
    float   CharParamZero[4];  // 21-24
    float   CharParamOne[4];  // 25-28
    float   CharParamTwo[4];  // 29-32
    float   CharParamThree[4];  // 33-36
    int32   Flags;  // 37
};

// SpellVisualPrecastTransitions -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct SpellVisualPrecastTransitionsEntry
{
    uint32  ID;  // 0
    char*   PrecastLoadAnimName;  // 1
    char*   PrecastHoldAnimName;  // 2
};

// Startup_Strings -- 19 cols, record_size 76, build 2.4.3.8606. INERT reference (not loaded).
struct Startup_StringsEntry
{
    uint32  ID;  // [dbd-only] 0
    char*   Name;  // 1
    char*   Message_lang[16];  // 2-17
// uint32  Message_lang_flags;  // 18
};

// Stationery -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct StationeryEntry
{
    uint32  ID;  // 0
    uint32  ItemID;  // 1
    char*   Texture;  // 2
    uint32  Flags;  // 3
};

// StringLookups -- 2 cols, record_size 8, build 2.4.3.8606. INERT reference (not loaded).
struct StringLookupsEntry
{
    int32   Id;  // 0
    char*   String;  // 1
};

// TerrainType -- 6 cols, record_size 24, build 2.4.3.8606. INERT reference (not loaded).
struct TerrainTypeEntry
{
    uint32  TerrainID;  // 0
    char*   TerrainDesc;  // 1
    uint32  FootstepSprayRun;  // 2
    uint32  FootstepSprayWalk;  // 3
    uint32  SoundID;  // 4
    uint32  Flags;  // 5
};

// TerrainTypeSounds -- 1 cols, record_size 4, build 2.4.3.8606. INERT reference (not loaded).
struct TerrainTypeSoundsEntry
{
    uint32  ID;  // 0
};

// TransportAnimation -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct TransportAnimationEntry
{
    uint32  ID;  // 0
    uint32  TransportID;  // 1
    uint32  TimeIndex;  // 2
    float   Pos[3];  // 3-5
    uint32  SequenceID;  // 6
};

// TransportPhysics -- 11 cols, record_size 44, build 2.4.3.8606. INERT reference (not loaded).
struct TransportPhysicsEntry
{
    int32   Id;  // 0
    float   WaveAmp;  // 1
    float   WaveTimeScale;  // 2
    float   RollAmp;  // 3
    float   RollTimeScale;  // 4
    float   PitchAmp;  // 5
    float   PitchTimeScale;  // 6
    float   MaxBank;  // 7
    float   MaxBankTurnSpeed;  // 8
    float   SpeedDampThresh;  // 9
    float   SpeedDamp;  // 10
};

// UISoundLookups -- 3 cols, record_size 12, build 2.4.3.8606. INERT reference (not loaded).
struct UISoundLookupsEntry
{
    uint32  ID;  // 0
    uint32  SoundID;  // 1
    char*   SoundName;  // 2
};

// UnitBlood -- 10 cols, record_size 40, build 2.4.3.8606. INERT reference (not loaded).
struct UnitBloodEntry
{
    uint32  ID;  // 0
    int32   CombatBloodSpurtFront[2];  // 1-2
    int32   CombatBloodSpurtBack[2];  // 3-4
    char*   GroundBlood[5];  // 5-9
};

// UnitBloodLevels -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct UnitBloodLevelsEntry
{
    uint32  ID;  // 0
    uint32  Violencelevel[3];  // 1-3
};

// VideoHardware -- 23 cols, record_size 92, build 2.4.3.8606. INERT reference (not loaded).
struct VideoHardwareEntry
{
    int32   ID;  // 0
    int32   VendorID;  // 1
    int32   DeviceID;  // 2
    int32   FarclipIdx;  // 3
    int32   TerrainLODDistIdx;  // 4
    int32   TerrainShadowLOD;  // 5
    int32   DetailDoodadDensityIdx;  // 6
    int32   DetailDoodadAlpha;  // 7
    int32   AnimatingDoodadIdx;  // 8
    int32   Trilinear;  // 9
    int32   NumLights;  // 10
    int32   Specularity;  // 11
    int32   WaterLODIdx;  // 12
    int32   ParticleDensityIdx;  // 13
    int32   UnitDrawDistIdx;  // 14
    int32   SmallCullDistIdx;  // 15
    int32   ResolutionIdx;  // 16
    int32   BaseMipLevel;  // 17
    char*   OglOverrides;  // 18
    char*   D3dOverrides;  // 19
    int32   FixLag;  // 20
    int32   Multisample;  // 21
    int32   Atlasdisable;  // 22
};

// VocalUISounds -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct VocalUISoundsEntry
{
    uint32  ID;  // 0
    int32   VocalUIEnum;  // 1
    uint32  RaceID;  // 2
    uint32  NormalSoundID[2];  // 3-4
    uint32  PissedSoundID[2];  // 5-6
};

// WeaponImpactSounds -- 23 cols, record_size 92, build 2.4.3.8606. INERT reference (not loaded).
struct WeaponImpactSoundsEntry
{
    uint32  ID;  // 0
    uint32  WeaponSubClassID;  // 1
    uint32  ParrySoundType;  // 2
    uint32  ImpactSoundID[10];  // 3-12
    uint32  CritImpactSoundID[10];  // 13-22
};

// WeaponSwingSounds2 -- 4 cols, record_size 16, build 2.4.3.8606. INERT reference (not loaded).
struct WeaponSwingSounds2Entry
{
    uint32  ID;  // 0
    int32   SwingType;  // 1
    int32   Crit;  // 2
    uint32  SoundID;  // 3
};

// Weather -- 7 cols, record_size 28, build 2.4.3.8606. INERT reference (not loaded).
struct WeatherEntry
{
    uint32  ID;  // 0
    uint32  AmbienceID;  // 1
    uint32  EffectType;  // 2
    float   EffectColor[3];  // 3-5
    char*   EffectTexture;  // 6
};

// WorldMapContinent -- 13 cols, record_size 52, build 2.4.3.8606. INERT reference (not loaded).
struct WorldMapContinentEntry
{
    uint32  ID;  // 0
    uint32  MapID;  // 1
    int32   LeftBoundary;  // 2
    int32   RightBoundary;  // 3
    int32   TopBoundary;  // 4
    int32   BottomBoundary;  // 5
    float   ContinentOffset[2];  // 6-7
    float   Scale;  // 8
    float   TaxiMin[2];  // 9-10
    float   TaxiMax[2];  // 11-12
};

// WorldMapOverlay -- 17 cols, record_size 68, build 2.4.3.8606. INERT reference (not loaded).
struct WorldMapOverlayEntry
{
    int32   ID;  // 0
    int32   MapAreaID;  // 1
    int32   AreaID[4];  // 2-5
    int32   MapPointX;  // 6
    int32   MapPointY;  // 7
    char*   TextureName;  // 8
    int32   TextureWidth;  // 9
    int32   TextureHeight;  // 10
    int32   OffsetX;  // 11
    int32   OffsetY;  // 12
    int32   HitRectTop;  // 13
    int32   HitRectLeft;  // 14
    int32   HitRectBottom;  // 15
    int32   HitRectRight;  // 16
};

// WorldMapTransforms -- 9 cols, record_size 36, build 2.4.3.8606. INERT reference (not loaded).
struct WorldMapTransformsEntry
{
    uint32  ID;  // 0
    uint32  MapID;  // 1
    float   RegionMin[2];  // 2-3
    float   RegionMax[2];  // 4-5
    uint32  NewMapID;  // 6
    float   RegionOffset[2];  // 7-8
};

// WorldStateUI -- 63 cols, record_size 252, build 2.4.3.8606. INERT reference (not loaded).
struct WorldStateUIEntry
{
    int32   ID;  // 0
    int32   MapID;  // 1
    int32   AreaID;  // 2
    char*   Icon;  // 3
    char*   String_lang[16];  // 4-19
// uint32  String_lang_flags;  // 20
    char*   Tooltip_lang[16];  // 21-36
// uint32  Tooltip_lang_flags;  // 37
    int32   FactionID;  // 38
    int32   StateVariable;  // 39
    int32   Type;  // 40
    char*   DynamicIcon;  // 41
    char*   DynamicTooltip_lang[16];  // 42-57
// uint32  DynamicTooltip_lang_flags;  // 58
    char*   ExtendedUI;  // 59
    int32   ExtendedUIStateVariable[3];  // 60-62
};

// WorldStateZoneSounds -- 8 cols, record_size 32, build 2.4.3.8606. INERT reference (not loaded).
struct WorldStateZoneSoundsEntry
{
    int32   WorldStateID;  // 0
    int32   WorldStateValue;  // 1
    int32   AreaID;  // 2
    int32   WMOAreaID;  // 3
    int32   ZoneIntroMusicID;  // 4
    int32   ZoneMusicID;  // 5
    int32   SoundAmbienceID;  // 6
    int32   SoundProviderPreferencesID;  // 7
};

// WowError_Strings -- 19 cols, record_size 76, build 2.4.3.8606. INERT reference (not loaded).
struct WowError_StringsEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    char*   Description_lang[16];  // 2-17
// uint32  Description_lang_flags;  // 18
};

// ZoneIntroMusicTable -- 5 cols, record_size 20, build 2.4.3.8606. INERT reference (not loaded).
struct ZoneIntroMusicTableEntry
{
    int32   ID;  // 0
    char*   Name;  // 1
    int32   SoundID;  // 2
    int32   Priority;  // 3
    int32   MinDelayMinutes;  // 4
};

// ZoneMusic -- 8 cols, record_size 32, build 2.4.3.8606. INERT reference (not loaded).
struct ZoneMusicEntry
{
    uint32  ID;  // 0
    char*   SetName;  // 1
    uint32  SilenceIntervalMin[2];  // 2-3
    uint32  SilenceIntervalMax[2];  // 4-5
    uint32  Sounds[2];  // 6-7
};

// gtNPCManaCostScaler -- 1 cols, record_size 4, build 2.4.3.8606. INERT reference (not loaded).
struct gtNPCManaCostScalerEntry
{
    float   Data;  // 0
};

// gtOCTRegenMP -- 1 cols, record_size 4, build 2.4.3.8606. INERT reference (not loaded).
struct gtOCTRegenMPEntry
{
    float   Data;  // 0
};

#endif
